head=[]
head.append('Title')
head.append('Imdb_id')#OMDB
head.append('Year')
head.append('Countries')
head.append('Languages')
head.append('Keywords')
head.append('Runtime')#OMDB
head.append('Genres')
head.append('Rated')#OMDB
head.append('Awards')#OMDB
head.append('Cast')
head.append('Editor')
head.append('Writer')
head.append('Production')
head.append('Director')
head.append('Producer')
head.append('Plot')#OMDB
head.append('Votes')
head.append('Rating')
head.append('R1')
head.append('R2')
head.append('R3')
head.append('R4')
head.append('R5')
head.append('R6')
head.append('R7')
head.append('R8')
head.append('R9')
head.append('R10')
head.append('Males')
head.append('Males Rating')
head.append('Females')
head.append('Females Rating')
head.append('Aged under 18')
head.append('Aged under 18 Rating')
head.append('Males under 18')
head.append('Males under 18 Rating')
head.append('Females under 18')
head.append('Females under 18 Rating')
head.append('Aged 18-29')
head.append('Aged 18-29 Rating')
head.append('Males Aged 18-29')
head.append('Males Aged 18-29 Rating')
head.append('Females Aged 18-29')
head.append('Females Aged 18-29 Rating')
head.append('Aged 30-44')
head.append('Aged 30-44 Rating')
head.append('Males Aged 30-44')
head.append('Males Aged 30-44 Rating')
head.append('Females Aged 30-44')
head.append('Females 30-44 Rating')
head.append('Aged 45+')
head.append('Aged 45+ Rating')
head.append('Males Aged 45+')
head.append('Males Aged 45+ Rating')
head.append('Females Aged 45+')
head.append('Females Aged 45+ Rating')
head.append('IMDb staff')
head.append('IMDb staff Rating')
head.append('Top 1000 voters')
head.append('Top 1000 voters Rating')
head.append('US users')
head.append('US users Rating')
head.append('Non-US users')
head.append('Non-US users Rating')
print head